import java.util.ArrayList;
import java.util.LinkedList;
import java.util.TreeSet;
import java.util.HashSet;

public class Time {
    static ArrayList<Integer> Chars = new ArrayList<>();
    static LinkedList<Integer> ll = new LinkedList<>();
    static TreeSet<Integer> ts = new TreeSet<>();
    static HashSet<Integer> hs = new HashSet<>();
    public static void TimeCount() {
        Chars.add(1);
        Chars.add(2);
        Chars.add(3);
        Chars.add(4);
        Chars.add(5);
        ll.add(1);
        ll.add(2);
        ll.add(3);
        ll.add(4);
        ll.add(5);
        ts.add(1);
        ts.add(2);
        ts.add(3);
        ts.add(4);
        ts.add(5);
        hs.add(1);
        hs.add(2);
        hs.add(3);
        hs.add(4);
        hs.add(5);
        long t1, t2, t;
        t1 = System.nanoTime();
        Chars.add(6);
        t2 = System.nanoTime();
        t = t2 - t1;
        System.out.println("ArrayList Add - " + t + " nanosec" );
        t1 = System.nanoTime();
        Chars.indexOf(6);
        t2 = System.nanoTime();
        t = t2 - t1;
        System.out.println("ArrayList Search - " + t + " nanosec" );
        t1 = System.nanoTime();
        Chars.remove(5);
        t2 = System.nanoTime();
        t = t2 - t1;
        System.out.println("ArrayList Delete - " + t + " nanosec" );
        t1 = System.nanoTime();
        ll.add(6);
        t2 = System.nanoTime();
        t = t2 - t1;
        System.out.println("LinkedList Add - " + t + " nanosec" );
        t1 = System.nanoTime();
        ll.indexOf(6);
        t2 = System.nanoTime();
        t = t2 - t1;
        System.out.println("LinkedList Search - " + t + " nanosec" );
        t1 = System.nanoTime();
        ll.remove(5);
        t2 = System.nanoTime();
        t = t2 - t1;
        System.out.println("LinkedList Delete - " + t + " nanosec" );
        t1 = System.nanoTime();
        ts.add(6);
        t2 = System.nanoTime();
        t = t2 - t1;
        System.out.println("TreeSet Add - " + t + " nanosec" );
        t1 = System.nanoTime();
        ts.contains(6);
        t2 = System.nanoTime();
        t = t2 - t1;
        System.out.println("TreeSet Search - " + t + " nanosec" );
        t1 = System.nanoTime();
        ts.remove(6);
        t2 = System.nanoTime();
        t = t2 - t1;
        System.out.println("TreeSet Delete - " + t + " nanosec" );
        t1 = System.nanoTime();
        hs.add(6);
        t2 = System.nanoTime();
        t = t2 - t1;
        System.out.println("HashSet Add - " + t + " nanosec" );
        t1 = System.nanoTime();
        hs.contains(6);
        t2 = System.nanoTime();
        t = t2 - t1;
        System.out.println("HashSet Search - " + t + " nanosec" );
        t1 = System.nanoTime();
        hs.remove(6);
        t2 = System.nanoTime();
        t = t2 - t1;
        System.out.println("HashSet Delete - " + t + " nanosec" );
    }
}
